/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trackme.ui;

/**
 *
 * @author L. Andrew Overholt
 */
public class TrackMeForm extends javax.swing.JFrame {

    /** Creates new form TrackMeForm */
    public TrackMeForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rBtnGroup_exerciseTypes = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_exercises = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_exerciseName = new javax.swing.JLabel();
        txt_exerciseName = new javax.swing.JTextField();
        rBtn_cardio = new javax.swing.JRadioButton();
        rBtn_bodyWeight = new javax.swing.JRadioButton();
        rBtn_resistance = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel_sessions = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_sessionsExerciseName = new javax.swing.JLabel();
        lbl_duration = new javax.swing.JLabel();
        lbl_distance = new javax.swing.JLabel();
        lbl_averageHR = new javax.swing.JLabel();
        lbl_bodyWeight = new javax.swing.JLabel();
        lbl_weight = new javax.swing.JLabel();
        lbl_sets = new javax.swing.JLabel();
        lbl_reps = new javax.swing.JLabel();
        txt_averageHR = new javax.swing.JTextField();
        txt_duration = new javax.swing.JTextField();
        txt_bodyWeight = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        txt_weight = new javax.swing.JTextField();
        txt_sets = new javax.swing.JTextField();
        txt_reps = new javax.swing.JTextField();
        txt_distance = new javax.swing.JTextField();
        cmboBx_exerciseName = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Exercise Name", "Exercise Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lbl_exerciseName.setText("Exercise Name:");

        txt_exerciseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_exerciseNameActionPerformed(evt);
            }
        });

        rBtnGroup_exerciseTypes.add(rBtn_cardio);
        rBtn_cardio.setText("Cardio");

        rBtnGroup_exerciseTypes.add(rBtn_bodyWeight);
        rBtn_bodyWeight.setText("Body Weight");

        rBtnGroup_exerciseTypes.add(rBtn_resistance);
        rBtn_resistance.setText("Resistance");

        jButton1.setText("Add/Update");

        jButton2.setText("Delete");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Manage Exercises");

        javax.swing.GroupLayout jPanel_exercisesLayout = new javax.swing.GroupLayout(jPanel_exercises);
        jPanel_exercises.setLayout(jPanel_exercisesLayout);
        jPanel_exercisesLayout.setHorizontalGroup(
            jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_exercisesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                    .addGroup(jPanel_exercisesLayout.createSequentialGroup()
                        .addGroup(jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_exercisesLayout.createSequentialGroup()
                                .addComponent(lbl_exerciseName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_exerciseName))
                            .addGroup(jPanel_exercisesLayout.createSequentialGroup()
                                .addComponent(rBtn_cardio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rBtn_bodyWeight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rBtn_resistance)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel_exercisesLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_exercisesLayout.setVerticalGroup(
            jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_exercisesLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_exerciseName)
                    .addComponent(txt_exerciseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtn_cardio)
                    .addComponent(rBtn_bodyWeight)
                    .addComponent(rBtn_resistance)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Exercises", jPanel_exercises);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Manage Sessions");

        lbl_date.setText("Date:");

        lbl_sessionsExerciseName.setText("Exercise:");

        lbl_duration.setText("Duration:");

        lbl_distance.setText("Distance:");

        lbl_averageHR.setText("Average HR:");

        lbl_bodyWeight.setText("Body Weight:");

        lbl_weight.setText("Weight:");

        lbl_sets.setText("Sets:");

        lbl_reps.setText("Reps:");

        txt_duration.setToolTipText("HH:MM:SS");

        txt_date.setToolTipText("YYYY-MM-DD");

        txt_distance.setToolTipText("Miles");

        cmboBx_exerciseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_save.setText("Save");

        btn_delete.setText("Delete");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Exercise", "Duration", "Distance", "Avg HR", "Body Weight", "Weight", "Sets", "Reps"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(90);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(95);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(2).setMinWidth(70);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(75);
            jTable2.getColumnModel().getColumn(2).setMaxWidth(80);
            jTable2.getColumnModel().getColumn(3).setMinWidth(60);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(65);
            jTable2.getColumnModel().getColumn(3).setMaxWidth(70);
            jTable2.getColumnModel().getColumn(4).setMinWidth(55);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(60);
            jTable2.getColumnModel().getColumn(4).setMaxWidth(65);
            jTable2.getColumnModel().getColumn(5).setMinWidth(80);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(85);
            jTable2.getColumnModel().getColumn(5).setMaxWidth(90);
            jTable2.getColumnModel().getColumn(6).setMinWidth(50);
            jTable2.getColumnModel().getColumn(6).setPreferredWidth(55);
            jTable2.getColumnModel().getColumn(6).setMaxWidth(60);
            jTable2.getColumnModel().getColumn(7).setMinWidth(35);
            jTable2.getColumnModel().getColumn(7).setPreferredWidth(40);
            jTable2.getColumnModel().getColumn(7).setMaxWidth(45);
            jTable2.getColumnModel().getColumn(8).setMinWidth(40);
            jTable2.getColumnModel().getColumn(8).setPreferredWidth(45);
            jTable2.getColumnModel().getColumn(8).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel_sessionsLayout = new javax.swing.GroupLayout(jPanel_sessions);
        jPanel_sessions.setLayout(jPanel_sessionsLayout);
        jPanel_sessionsLayout.setHorizontalGroup(
            jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_date)
                            .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_averageHR)
                                    .addComponent(lbl_distance)
                                    .addComponent(lbl_duration)
                                    .addComponent(lbl_sessionsExerciseName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_duration, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txt_distance, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txt_averageHR)
                                    .addComponent(cmboBx_exerciseName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addComponent(lbl_reps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_reps, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addComponent(lbl_sets)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_sets, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addComponent(lbl_weight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addComponent(lbl_bodyWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_sessionsLayout.setVerticalGroup(
            jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_date)
                                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_sessionsExerciseName)
                                    .addComponent(cmboBx_exerciseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_duration)
                                    .addComponent(txt_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_distance)
                                    .addComponent(txt_distance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_averageHR)
                            .addComponent(txt_averageHR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_bodyWeight)
                            .addComponent(txt_bodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_weight)
                            .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sets)
                            .addComponent(txt_sets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_reps)
                            .addComponent(txt_reps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sessions", jPanel_sessions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("jTabbedPane1");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_exerciseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_exerciseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_exerciseNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackMeForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackMeForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackMeForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackMeForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackMeForm().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmboBx_exerciseName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel_exercises;
    private javax.swing.JPanel jPanel_sessions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_averageHR;
    private javax.swing.JLabel lbl_bodyWeight;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_distance;
    private javax.swing.JLabel lbl_duration;
    private javax.swing.JLabel lbl_exerciseName;
    private javax.swing.JLabel lbl_reps;
    private javax.swing.JLabel lbl_sessionsExerciseName;
    private javax.swing.JLabel lbl_sets;
    private javax.swing.JLabel lbl_weight;
    private javax.swing.ButtonGroup rBtnGroup_exerciseTypes;
    private javax.swing.JRadioButton rBtn_bodyWeight;
    private javax.swing.JRadioButton rBtn_cardio;
    private javax.swing.JRadioButton rBtn_resistance;
    private javax.swing.JTextField txt_averageHR;
    private javax.swing.JTextField txt_bodyWeight;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_distance;
    private javax.swing.JTextField txt_duration;
    private javax.swing.JTextField txt_exerciseName;
    private javax.swing.JTextField txt_reps;
    private javax.swing.JTextField txt_sets;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables


    
}
