/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trackme.ui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trackme.business.Exercise;
import trackme.business.WorkoutSession;
import trackme.db.ExerciseDB;
import trackme.db.WorkoutSessionDB;

/**
 *
 * @author L. Andrew Overholt
 */
public class TrackMeForm extends javax.swing.JFrame {

    /** Creates new form TrackMeForm */
    public TrackMeForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rBtnGroup_exerciseTypes = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel_exercises = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Exercises = new javax.swing.JTable();
        lbl_exerciseName = new javax.swing.JLabel();
        txt_exe_Name = new javax.swing.JTextField();
        rBtn_exe_cardio = new javax.swing.JRadioButton();
        rBtn_exe_bodyWeight = new javax.swing.JRadioButton();
        rBtn_exe_resistance = new javax.swing.JRadioButton();
        btn_exe_add = new javax.swing.JButton();
        btn_exe_delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_exe_update = new javax.swing.JButton();
        jPanel_sessions = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        lbl_sessionsExerciseName = new javax.swing.JLabel();
        lbl_duration = new javax.swing.JLabel();
        lbl_distance = new javax.swing.JLabel();
        lbl_averageHR = new javax.swing.JLabel();
        lbl_bodyWeight = new javax.swing.JLabel();
        lbl_weight = new javax.swing.JLabel();
        lbl_sets = new javax.swing.JLabel();
        lbl_reps = new javax.swing.JLabel();
        txt_averageHR = new javax.swing.JTextField();
        txt_duration = new javax.swing.JTextField();
        txt_bodyWeight = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        txt_weight = new javax.swing.JTextField();
        txt_sets = new javax.swing.JTextField();
        txt_reps = new javax.swing.JTextField();
        txt_distance = new javax.swing.JTextField();
        cmboBx_exerciseName = new javax.swing.JComboBox<>();
        btn_ses_add = new javax.swing.JButton();
        btn_ses_delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Sessions = new javax.swing.JTable();
        btn_ses_update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome to TrackMe!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(395, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel1);

        tbl_Exercises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Exercise Name", "Exercise Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Exercises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_exe_onRecordClick(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Exercises);

        lbl_exerciseName.setText("Exercise Name:");

        txt_exe_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_exe_NameActionPerformed(evt);
            }
        });

        rBtnGroup_exerciseTypes.add(rBtn_exe_cardio);
        rBtn_exe_cardio.setSelected(true);
        rBtn_exe_cardio.setText("Cardio");
        rBtn_exe_cardio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtn_exe_cardioActionPerformed(evt);
            }
        });

        rBtnGroup_exerciseTypes.add(rBtn_exe_bodyWeight);
        rBtn_exe_bodyWeight.setText("Body Weight");
        rBtn_exe_bodyWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtn_exe_bodyWeightActionPerformed(evt);
            }
        });

        rBtnGroup_exerciseTypes.add(rBtn_exe_resistance);
        rBtn_exe_resistance.setText("Resistance");
        rBtn_exe_resistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtn_exe_resistanceActionPerformed(evt);
            }
        });

        btn_exe_add.setText("Add");
        btn_exe_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exe_addActionPerformed(evt);
            }
        });

        btn_exe_delete.setText("Delete");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Manage Exercises");

        btn_exe_update.setText("Update");
        btn_exe_update.setFocusable(false);
        btn_exe_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exe_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_exercisesLayout = new javax.swing.GroupLayout(jPanel_exercises);
        jPanel_exercises.setLayout(jPanel_exercisesLayout);
        jPanel_exercisesLayout.setHorizontalGroup(
            jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_exercisesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                    .addGroup(jPanel_exercisesLayout.createSequentialGroup()
                        .addGroup(jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_exercisesLayout.createSequentialGroup()
                                .addComponent(lbl_exerciseName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_exe_Name))
                            .addGroup(jPanel_exercisesLayout.createSequentialGroup()
                                .addComponent(rBtn_exe_cardio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rBtn_exe_bodyWeight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rBtn_exe_resistance)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_exe_delete)
                            .addGroup(jPanel_exercisesLayout.createSequentialGroup()
                                .addComponent(btn_exe_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_exe_update)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel_exercisesLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_exercisesLayout.setVerticalGroup(
            jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_exercisesLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_exerciseName)
                    .addComponent(txt_exe_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exe_add)
                    .addComponent(btn_exe_update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_exercisesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtn_exe_cardio)
                    .addComponent(rBtn_exe_bodyWeight)
                    .addComponent(rBtn_exe_resistance)
                    .addComponent(btn_exe_delete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Exercises", jPanel_exercises);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Manage Sessions");

        lbl_date.setText("Date:");

        lbl_sessionsExerciseName.setText("Exercise:");

        lbl_duration.setText("Duration:");

        lbl_distance.setText("Distance:");

        lbl_averageHR.setText("Average HR:");

        lbl_bodyWeight.setText("Body Weight:");

        lbl_weight.setText("Weight:");

        lbl_sets.setText("Sets:");

        lbl_reps.setText("Reps:");

        txt_duration.setToolTipText("HH:MM:SS");

        txt_date.setToolTipText("YYYY-MM-DD");

        txt_distance.setToolTipText("Miles");

        cmboBx_exerciseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_ses_add.setText("Add");

        btn_ses_delete.setText("Delete");

        tbl_Sessions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Exercise", "Duration", "Distance", "Avg HR", "Body Weight", "Weight", "Sets", "Reps"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Sessions.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_Sessions);
        if (tbl_Sessions.getColumnModel().getColumnCount() > 0) {
            tbl_Sessions.getColumnModel().getColumn(0).setMinWidth(90);
            tbl_Sessions.getColumnModel().getColumn(0).setPreferredWidth(95);
            tbl_Sessions.getColumnModel().getColumn(0).setMaxWidth(100);
            tbl_Sessions.getColumnModel().getColumn(2).setMinWidth(70);
            tbl_Sessions.getColumnModel().getColumn(2).setPreferredWidth(75);
            tbl_Sessions.getColumnModel().getColumn(2).setMaxWidth(80);
            tbl_Sessions.getColumnModel().getColumn(3).setMinWidth(60);
            tbl_Sessions.getColumnModel().getColumn(3).setPreferredWidth(65);
            tbl_Sessions.getColumnModel().getColumn(3).setMaxWidth(70);
            tbl_Sessions.getColumnModel().getColumn(4).setMinWidth(55);
            tbl_Sessions.getColumnModel().getColumn(4).setPreferredWidth(60);
            tbl_Sessions.getColumnModel().getColumn(4).setMaxWidth(65);
            tbl_Sessions.getColumnModel().getColumn(5).setMinWidth(80);
            tbl_Sessions.getColumnModel().getColumn(5).setPreferredWidth(85);
            tbl_Sessions.getColumnModel().getColumn(5).setMaxWidth(90);
            tbl_Sessions.getColumnModel().getColumn(6).setMinWidth(50);
            tbl_Sessions.getColumnModel().getColumn(6).setPreferredWidth(55);
            tbl_Sessions.getColumnModel().getColumn(6).setMaxWidth(60);
            tbl_Sessions.getColumnModel().getColumn(7).setMinWidth(35);
            tbl_Sessions.getColumnModel().getColumn(7).setPreferredWidth(40);
            tbl_Sessions.getColumnModel().getColumn(7).setMaxWidth(45);
            tbl_Sessions.getColumnModel().getColumn(8).setMinWidth(40);
            tbl_Sessions.getColumnModel().getColumn(8).setPreferredWidth(45);
            tbl_Sessions.getColumnModel().getColumn(8).setMaxWidth(50);
        }

        btn_ses_update.setText("Update");
        btn_ses_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ses_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_sessionsLayout = new javax.swing.GroupLayout(jPanel_sessions);
        jPanel_sessions.setLayout(jPanel_sessionsLayout);
        jPanel_sessionsLayout.setHorizontalGroup(
            jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_date)
                            .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_averageHR)
                                    .addComponent(lbl_distance)
                                    .addComponent(lbl_duration)
                                    .addComponent(lbl_sessionsExerciseName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_duration, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txt_distance, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txt_averageHR)
                                    .addComponent(cmboBx_exerciseName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addComponent(lbl_reps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_reps, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addComponent(lbl_sets)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_sets, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addComponent(lbl_weight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addComponent(lbl_bodyWeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_bodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ses_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ses_add, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ses_update, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_sessionsLayout.setVerticalGroup(
            jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_ses_add, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ses_update, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ses_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_date)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sessionsExerciseName)
                            .addComponent(cmboBx_exerciseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_duration)
                            .addComponent(txt_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_distance)
                            .addComponent(txt_distance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_averageHR)
                            .addComponent(txt_averageHR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_sessionsLayout.createSequentialGroup()
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_bodyWeight)
                            .addComponent(txt_bodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_weight)
                            .addComponent(txt_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sets)
                            .addComponent(txt_sets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_sessionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_reps)
                            .addComponent(txt_reps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sessions", jPanel_sessions);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("jTabbedPane1");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_exe_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_exe_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_exe_NameActionPerformed

    private void btn_exe_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exe_addActionPerformed
        addExercise();
    }//GEN-LAST:event_btn_exe_addActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        refresh();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btn_ses_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ses_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ses_updateActionPerformed

    private void btn_exe_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exe_updateActionPerformed
        updateExercise();
    }//GEN-LAST:event_btn_exe_updateActionPerformed

    private void rBtn_exe_cardioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtn_exe_cardioActionPerformed
        refreshRadioButtonExeType();
    }//GEN-LAST:event_rBtn_exe_cardioActionPerformed

    private void rBtn_exe_bodyWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtn_exe_bodyWeightActionPerformed
        refreshRadioButtonExeType();
    }//GEN-LAST:event_rBtn_exe_bodyWeightActionPerformed

    private void rBtn_exe_resistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtn_exe_resistanceActionPerformed
        refreshRadioButtonExeType();
    }//GEN-LAST:event_rBtn_exe_resistanceActionPerformed

    private void tbl_exe_onRecordClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_exe_onRecordClick
        displayExercise();
    }//GEN-LAST:event_tbl_exe_onRecordClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info: javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackMeForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackMeForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackMeForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackMeForm.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackMeForm().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exe_add;
    private javax.swing.JButton btn_exe_delete;
    private javax.swing.JButton btn_exe_update;
    private javax.swing.JButton btn_ses_add;
    private javax.swing.JButton btn_ses_delete;
    private javax.swing.JButton btn_ses_update;
    private javax.swing.JComboBox<String> cmboBx_exerciseName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_exercises;
    private javax.swing.JPanel jPanel_sessions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_averageHR;
    private javax.swing.JLabel lbl_bodyWeight;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_distance;
    private javax.swing.JLabel lbl_duration;
    private javax.swing.JLabel lbl_exerciseName;
    private javax.swing.JLabel lbl_reps;
    private javax.swing.JLabel lbl_sessionsExerciseName;
    private javax.swing.JLabel lbl_sets;
    private javax.swing.JLabel lbl_weight;
    private javax.swing.ButtonGroup rBtnGroup_exerciseTypes;
    private javax.swing.JRadioButton rBtn_exe_bodyWeight;
    private javax.swing.JRadioButton rBtn_exe_cardio;
    private javax.swing.JRadioButton rBtn_exe_resistance;
    private javax.swing.JTable tbl_Exercises;
    private javax.swing.JTable tbl_Sessions;
    private javax.swing.JTextField txt_averageHR;
    private javax.swing.JTextField txt_bodyWeight;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_distance;
    private javax.swing.JTextField txt_duration;
    private javax.swing.JTextField txt_exe_Name;
    private javax.swing.JTextField txt_reps;
    private javax.swing.JTextField txt_sets;
    private javax.swing.JTextField txt_weight;
    // End of variables declaration//GEN-END:variables


    
    
    
    
    
    
    
    
    
    
    /**
     * ==================================================================================================================
     * @author L. Andrew Overholt  My code begins here
     * ==================================================================================================================
     */
    
    
    
    
    
    ////////////////////////////////////////////////////////////////////////////////// VARIABLES
    
    private static ExerciseDB exerciseDB = new ExerciseDB();
    ArrayList<Exercise> exercises = exerciseDB.getAll();
    private static WorkoutSessionDB workoutSessionDB = new WorkoutSessionDB();
    ArrayList<WorkoutSession> sessions = workoutSessionDB.getAll();
    
    private static int rb_exe_type = 1; // Cardio is selected by default
    private static Exercise selectedExercise;
    
    
    
    
    
    ////////////////////////////////////////////////////////////////////////////////// METHODS
    
    /**
     * Erases the text fields and refreshes the data in the table 
     */
    public void refresh() {
        //clear();
        
        
        /**
         * refresh the Exercises table
         */
        exercises = exerciseDB.getAll();
        DefaultTableModel exercisesTableModel = (DefaultTableModel) tbl_Exercises.getModel();
        exercisesTableModel.setRowCount(0);
        
        try {
            for (Exercise e: exercises) {
                exercisesTableModel.addRow(new Object[]{e.getName(), e.getTypeID()});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        int exercisesRowNum = exercisesTableModel.getRowCount();
        
        // Makes the table look nicer by having the white rows fill out the visible
        // part instead of having grey space
        while (exercisesRowNum < 18){
            exercisesTableModel.addRow(new Object[] {"",""});
            exercisesRowNum++;
        }
        
        /**
         * refresh the Sessions table
         */
        sessions = workoutSessionDB.getAll();
        DefaultTableModel sessionsTableModel = (DefaultTableModel) tbl_Sessions.getModel();
        sessionsTableModel.setRowCount(0);
        
        try {
            for (WorkoutSession s: sessions) {
                sessionsTableModel.addRow(
                        new Object[]{
                            s.getDate(), s.getExerciseName(), s.getDuration(), s.getDistance(), 
                            s.getAverageHeartRate(), s.getBodyWeight(), s.getWeight(), s.getSets(), s.getReps()
                        });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        int sessionsRowNum = sessionsTableModel.getRowCount();
        
        // Makes the table look nicer by having the white rows fill out the visible
        // part instead of having grey space
        while (sessionsRowNum < 13){
            sessionsTableModel.addRow(new Object[] {"","","","","","","","",""});
            sessionsRowNum++;
        }
    }
    
    /**
     * <h2>When is it called?</h2>
     * <p>Every time a radio button in the "rBtnGroup_exerciseTypes" is clicked.</p>
     * <br><br>
     * <h2>What does it do?</h2>
     * <p>Sets the variable "rb_exe_type" to the correct String</p>
     */
    public void refreshRadioButtonExeType(){
        if (rBtn_exe_cardio.isSelected()) {
            rb_exe_type = 1;
        } else if (rBtn_exe_bodyWeight.isSelected()) {
            rb_exe_type = 2;
        } else if (rBtn_exe_resistance.isSelected()) {
            rb_exe_type = 3;
        }
    }
    
    /**
     * <h2>When is it called?</h2>
     * When the "Add" button is clicked in the "Exercise" tab.
     * <br><br>
     * <h2>What does it do?</h2>
     * <ol>
     *  <li>Collect the data</li>
     *  <li>Validate the data</li>
     *  <li>Adds an exercise to the database</li>
     *  <li>Calls the refresh method</li>
     * </ol>
     */
    public void addExercise() {
        
        // Collect data and store in Variables
        String eName = txt_exe_Name.getText(); // Exercises: Name of exercise
        int eType = rb_exe_type; // Exercises: Type of exercise
        
        // Check that a name was entered, then try to add to database
        if (eName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                                "You must enter a valid string!", 
                                "Add Failure", 
                                JOptionPane.ERROR_MESSAGE);
        } else {
              try {
                  exerciseDB.add(eName, eType);
              } catch (Exception e) {
                  JOptionPane.showMessageDialog(this, 
                                "There is already an exercise with this name!", 
                                "Add Failure", 
                                JOptionPane.ERROR_MESSAGE);
              }
        }
        
        // Refresh the table
        refresh();
        clear();
    }
    
    /**
     * <h2>When is it called?</h2>
     * When a record is clicked in the Exercise table
     * <br><br>
     * <h2>What does it do?</h2>
     * <ol>
     *  <li>Gets the selected row number</li>
     *  <li>Gets the correct object using the row number</li>
     *  <li>Sets the Values in the form using the objects properties</li>
     * </ol>
     */
    public void displayExercise() {
        int rowNum = tbl_Exercises.getSelectedRow(); // get the selected row number
        selectedExercise = exercises.get(rowNum); // set the selectedExercise using the rowNum
        
        txt_exe_Name.setText(selectedExercise.getName());
        rb_exe_type = selectedExercise.getTypeID();
        switch (rb_exe_type) {
            case 1 -> rBtn_exe_cardio.setSelected(true);
            case 2 -> rBtn_exe_bodyWeight.setSelected(true);
            case 3 -> rBtn_exe_resistance.setSelected(true);
        }
        
    }
    
    /**
     * <h2>When is it called?</h2>
     * When the "Update" button is clicked in the Exercise tab
     * <br><br>
     * <h2>What does it do?</h2>
     * <ol>
     *  <li>Collect data from form</li>
     *  <li>Use data to set Properties of selectedExercise</li>
     *  <li>Sends the object to ExerciseDB's "Update" method</li>
     *  <li>Refreshes the table</li>
     * </ol>
     */
    public void updateExercise() {
        
        // Collect data and store in Variables
        String eName = txt_exe_Name.getText(); // Exercises: Name of exercise
        int eType = rb_exe_type; // Exercises: Type of exercise
        boolean unique;
        
        // Check that a name was entered, then try to add to database
        if (eName.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                                "You must enter a valid string!", 
                                "Update Failure", 
                                JOptionPane.ERROR_MESSAGE);
        } else {
            selectedExercise.setName(eName);
            selectedExercise.setTypeID(eType);
            unique = exerciseDB.update(selectedExercise);
            
            //TODO FIX BUG: doesnt show error message when changing name to the same as another records name
            if (!unique) {
                JOptionPane.showMessageDialog(this, 
                                "There is already an exercise with this name!", 
                                "Update Failure", 
                                JOptionPane.ERROR_MESSAGE);
            }
        }
        
        // Refresh the table
        refresh();
        clear();
    }

    /**
     * <h2>When is it called?</h2>
     * Whenever the fields need to be cleared
     * <br><br>
     * <h2>What does it do?</h2>
     * Clears all the fields
     */
    private void clear() {
        txt_exe_Name.setText("");
    }
    /**
     * ==================================================================================================================
     * @author L. Andrew Overholt  My code ends here
     * ==================================================================================================================
     */
    
}
